#!/usr/bin/bash

declare -A db_names
db_names[local]=infinite-closet-dev
db_names[dev]=infinite-closet-dev
db_names[prod]=infinite-closet

declare -A db_users
db_users[local]=test
db_users[dev]=test
db_users[prod]=infinite-closet

docker exec -i ${@:2} ${1}_db_1 psql -d ${db_names[$1]} -U ${db_users[$1]}
