version: '3.8'

services:
  app:
    build:
      context: .
      target: prod
    ports:
      - 3000:3000
      - 1337:1337
    environment:
      - SERVER_PORT=1337
      - CONNECTIONSTRING=postgres://db:5432
    volumes:
      - ./:/app
    command: yarn run develop
    env_file:
      - backend/.env.development

  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres/data
    restart:
      always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: infinite-closet-dev

  nginx:
    image: nginx:1.21
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
    command: nginx -g 'daemon off;'
    restart: always

volumes:
  postgres:
