version: '3.3'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      NEXT_PUBLIC_FRONTEND: 'https://dev.infinitecloset.co.uk'
      NEXT_PUBLIC_BACKEND: 'https://api.dev.infinitecloset.co.uk'
      NEXT_PUBLIC_FIREBASE_CONFIG: '{"apiKey":"AIzaSyC3eakvWXGZVM2vKN69pXViyPsHyQghCys","authDomain":"infinite-closet-1614373277543.firebaseapp.com","projectId":"infinite-closet-1614373277543","storageBucket":"infinite-closet-1614373277543.appspot.com","messagingSenderId":"703454257680","appId":"1:703454257680:web:ffd5aeb011088bfe6b6095","measurementId":"G-K4XJMWSGN9"}'
      NEXT_PUBLIC_STRIPE_KEY: pk_test_51Ikb9lDnNgAk4A84M2EKzMFOlpQG65VHqqw8ZKlY8KwfgGHLEadvakIIJM7dA6HzVewnWZvJ2BPR9ZGq9SwfKBFJ00PTz0SIz5
    command: yarn run develop
    working_dir: /app

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "127.0.0.1:1338:1337"
    command: yarn run develop
    working_dir: /app
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: infinite-closet-dev
      DATABASE_PASSWORD: test
      DATABASE_PORT: 5432
      DATABASE_USERNAME: test
      FRONTEND_DOMAIN: dev.infinitecloset.co.uk
      BACKEND_DOMAIN: api.dev.infinitecloset.co.uk
      NODE_ENV: development
      STRIPE_KEY: sk_test_51Ikb9lDnNgAk4A84a08Vrtj9h0K7Zg6C3HLSEhbZXRkC2E3wX2y9JDo67TOZI8spmVj4nvaHSamVwiKUokS9Kg5S00whW8RV3K
    volumes:
      - ../backend/public:/app/public

  db:
    environment:
      POSTGRES_DB: infinite-closet-dev
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  postgres:
