version: '3.3'

services:
  frontend:
    environment:
      NEXT_PUBLIC_FRONTEND: 'https://infinitecloset.treywilkinson.com'
      NEXT_PUBLIC_BACKEND: 'https://api.infinitecloset.treywilkinson.com'

  backend:
    environment:
      FRONTEND_DOMAIN: infinitecloset.treywilkinson.com
    command: yarn run develop
