#!/bin/bash

case $1 in
    check)
        curl -s -X GET -u t-wilkinson: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 https://api.github.com/repos/t-wilkinson/infinite-closet/commits/dev/check-runs | python -c '
import json
import sys
for run in json.load(sys.stdin)["check_runs"]:
    # print(json.dumps(run, indent=4, sort_keys=True))
    print(run["completed_at"], run["status"], run["conclusion"])
'
        ;;

    *)
        declare -A profiles
        profiles[prod]="-p prod -f docker/compose.yml -f docker/compose.prod.yml"
        profiles[dev]="-p dev -f docker/compose.yml -f docker/compose.dev.yml"
        profiles[local]="-p local -f docker/compose.yml -f docker/compose.dev.yml -f docker/compose.local.yml"
        profiles[test]="-p local -f docker/compose.yml -f docker/compose.dev.yml -f docker/compose.test.yml"

        declare -A nodeenv
        nodeenv[prod]=production
        nodeenv[dev]=development
        nodeenv[local]=development
        nodeenv[test]=development

        NODE_ENV=${nodeenv[$1]} COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose ${profiles[$1]} ${@:2}
        ;;
esac
