#!/bin/bash
declare -A profiles
profiles[prod]="-p prod -f docker/docker-compose.yml -f docker/docker-compose.prod.yml"
profiles[dev]="-p dev -f docker/docker-compose.yml -f docker/docker-compose.dev.yml"
profiles[local]="-p local -f docker/docker-compose.yml -f docker/docker-compose.dev.yml -f docker/docker-compose.local.yml"

COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose ${profiles[$1]} ${@:2}
