export const mockProduct = {
  id: 1234567890,
  name: 'Product Name',
  slug: 'product-name',
  designer: { name: 'Designer Name', slug: 'designer-name' },
  shortRentalPrice: 10.0,
  longRentalPrice: 10.0,
  retailPrice: 10.0,
  purchasePrice: 10.0,
  images: [],
  sizes: [{ id: '1', quantity: 1, size: 'MD' }],
  details: 'Product details',
  stylistNotes: 'Stylist notes',
  sizingNotes: 'Sizing notes',
  categories: [],
  colors: [],
  fits: [],
  occasions: [],
  styles: [],
  weather: [],
  categories_: '',
  colors_: '',
  fits_: '',
  occasions_: '',
  styles_: '',
  weather_: '',
  created_by: '',
  updated_at: '',
  published_at: '',
}
