export default {
  id: '18',
  username: 'joe-deer-1234',
  email: 'joe.deer@gmail.com',
  provider: 'string',
  password: 'password123',
  resetPasswordToken: 'string',
  confirmationToken: 'string',
  confirmed: true,
  blocked: false,
  customer: '',
  firstName: 'Joe',
  lastName: 'Deer',
  phoneNumber: '1234567890',
  addresses: [],
  orders: [],
  chestSize: '60',
  hipsSize: '',
  waistSize: '',
  dressSize: '',
  height: '',
  weight: '',
  dateOfBirth: '',
  created_by: '',
  updated_at: '',
  published_at: '',
}
