#!/usr/bin/env bash
# Run psql command inside docker container

if [[ $1 == -h ]]; then
    cat <<EOF
Usage: $(basename "$0") (local|dev|prod) [OPTIONS]
Run psql command inside docker container.

Examples:
   ./exec_psql local -it   # Runs psql shell interactively
   ./exec_psql prod -i < ./psql-commands   # Runs commands in "./psql-commands" in psql shell
EOF
    exit 0
fi

declare -A db_names
db_names[local]=infinite-closet-dev
db_names[dev]=infinite-closet-dev
db_names[prod]=infinite-closet

declare -A db_users
db_users[local]=test
db_users[dev]=test
db_users[prod]=infinite-closet

declare -A db_containers
db_containers[local]=local_db_1
db_containers[dev]=dev_db_1
db_containers[prod]=prod_db_1

docker exec -i ${@:2} ${db_containers[$1]} psql -d ${db_names[$1]} -U ${db_users[$1]}
