#!/usr/bin/env python
"""Move maillist email contacts to database

Emails are expected to be downloaded from gmail.
Should be ran inside directory with emails.

At this point we have multiple emails from newsletters and waitlists stored as emails.
This script converts these emails to valid SQL insert statements to be fed into the database.
"""
import os
import re
import collections
import json

emails = {}

for file_name in os.listdir('.'):
    if not file_name.endswith('.eml'):
        continue
    is_field = re.compile('^([^:]+): ?(.*)$')

    with open(file_name, 'r') as file:
        lines = [line.rstrip() for line in file]
        (start, end) = [i for i, line in enumerate(lines) if line == ""][1:3]
        lines = lines[start+1:end]
        lines = [line for line in lines if not re.search(r'=|>', line)]

        fields = collections.defaultdict(str)
        fields['Email'] = "NULL"
        fields['Context'] = 'newsletter' if re.search(
            r'Newsletter', file_name) else 'waitlist'
        key = ""
        for line in lines:
            line = line.replace("'", "''")
            match = is_field.search(line)
            if match:
                key = match[1]
                fields[key] = match[2]
            else:
                fields[key] += line
        emails[fields['Email']] = {**fields}


inserts = []
for client, email in emails.items():
    email_json = json.dumps(email)
    inserts.append(f"('{email['Context']}', '{client}', '{email_json}')")

statement = f'INSERT INTO "contact" (context, contact, metadata) VALUES {", ".join(inserts)};'
print(statement)
