#!/bin/env bash

monitor() {
    ssh infinitecloset  "echo; echo; echo; echo $1; exec ${@:2}"
}

monitor DOCKER docker ps &
monitor IP ip a &
monitor LAST 'last | tail -10' &
monitor UPTIME uptime &
monitor DF df / -h &
monitor VMSTAT 'vmstat -s; vmstat -w -Sk; vmstat -d -w' &
monitor SS 'ss -tunp' &
