#!/usr/bin/env bash
# Update local database from server database
#
# Connects to server database through ssh and `pg_dump` data to computer

if [[ $(basename $(pwd)) != 'infinite-closet' ]]; then
    echo 'Please run in root project directory'
    exit 1
fi

# Sync uploaded photos
# rsync -avz infinitecloset:/www/infinite-closet/main/backend/public/uploads/ ./backend/public/uploads

# Sync the database
ssh infinitecloset 'docker exec prod_db_1 pg_dump -d infinite-closet -U infinite-closet -CcO | bzip2'  | bunzip2 | scripts/exec-psql "local" -i

scripts/exec-psql "local" -i <<SQL
\c postgres
DROP DATABASE IF EXISTS "infinite-closet-dev-old";
ALTER DATABASE "infinite-closet-dev" RENAME TO "infinite-closet-dev-old";
ALTER DATABASE "infinite-closet" RENAME TO "infinite-closet-dev";
SQL
