name: Infinite Closet CI

on:
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      - name: Prepare ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >> ~/.ssh/config <<EOF
          Host staging
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port 2222
          EOF

      - name: Pull any changes
        env:
          GITHUB_BRANCH: dev # ${{ github.ref }}
        run: |
          ssh -T staging<<EOF
          # branch=${GITHUB_BRANCH##*/}
          pwd
          mkdir -p /www/infinite-closet/dev
          cd /www/infinite-closet/dev
          git fetch --all
          git switch main
          git pull origin main
          EOF

      - name: Build frontend
        run: |
          ssh -T staging <<EOF
          pwd
          cd /www/infinite-closet/dev/frontend
          yarn install
          # yarn run build
          EOF

      - name: Build backend
        run: |
          ssh -T staging <<EOF
          pwd
          cd /www/infinite-closet/dev/backend
          yarn install
          # yarn run build
          EOF
