name: Infinite Closet CI

on:
  push:
    branches: [ main, dev, staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >> ~/.ssh/config <<EOF
          Host staging
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port 2222
          EOF

      - name: Setup env vars
        env:
          GITHUB_BRANCH: ${{ github.ref }}
        run: |
          echo "branch=${GITHUB_BRANCH##*/}" >> $GITHUB_ENV

      - name: Add changes to server
        run: |
          ssh -T staging<<EOF
          mkdir -p "/www/infinite-closet/${{ env.branch }}"
          cd "/www/infinite-closet/${{ env.branch }}"
          git fetch --all
          git switch "${{ env.branch }}"
          git pull origin "${{ env.branch }}"
          EOF

      - name: Build production server
        if: ${{ env.branch == 'main' }}
        run: |
          ssh -T staging <<EOF
          cd "/www/infinite-closet/${{ env.branch }}"

          docker/run prod build --paralell
          docker/run prod up

          EOF

      - name: Run develop server
        if: ${{ env.branch == 'dev' }}
        run: |
          ssh -T staging <<EOF
          cd "/www/infinite-closet/${{ env.branch }}"
          docker/run dev up
          EOF

      - name: Run staging
        if: ${{ env.branch == 'staging' }}
        run: |
          ssh -T staging <<EOF
          cd "/www/infinite-closet/${{ env.branch }}"
          EOF
