name: Infinite Closet CI

on:
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >> ~/.ssh/config <<EOF
          Host staging
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port 2222
          EOF

      - name: Setup env vars
        env:
          GITHUB_BRANCH: ${{ github.ref }}
        run: |
          echo "branch=${GITHUB_BRANCH##*/}" >> $GITHUB_ENV

      - name: Add changes to server
        run: |
          ssh -T staging<<EOF
          mkdir -p "/www/infinite-closet/${{ env.branch }}"
          cd "/www/infinite-closet/${{ env.branch }}"
          git fetch --all
          git switch "${{ env.branch }}"
          git pull origin "${{ env.branch }}"
          yarn install
          (cd frontend && yarn install && yarn run sts)
          (cd backend && yarn install)
          EOF

      - name: Build
        if: ${{ env.branch == 'main' }}
        run: |
          ssh -T staging <<EOF
          cd "/www/infinite-closet/${{ env.branch }}"

          (cd frontend
            yarn run build

            if [ "$(pm2 id main:frontend) "= "[]" ]; then
              pm2 start main:frontend
            else
              pm2 reload main:frontend
            fi
          )

          (cd backend
            yarn run build

            if [ "$(pm2 id main:backend) "= "[]" ]; then
              pm2 start main:backend
            else
              pm2 reload main:backend
            fi
          )
          EOF

      - name: Run develop server
        if: ${{ env.branch == 'dev' }}
        run: |
          ssh -T staging <<EOF
          cd "/www/infinite-closet/${{ env.branch }}"

          if [ "$(pm2 id main:backend) "= "[]" ]; then
            pm2 start main:backend
          else
            pm2 reload main:backend
          fi
          EOF
