name: Infinite Closet CI

on:
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >> ~/.ssh/config <<EOF
          Host staging
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port 2222
          EOF

      - name: Pull any changes
        env:
          GITHUB_BRANCH: ${{ github.ref }}
        run: |
          ssh -T staging<<EOF
          branch="${GITHUB_BRANCH##*/}"
          mkdir -p "/www/infinite-closet/$branch"
          cd "/www/infinite-closet/$branch"
          git fetch --all
          git switch "$branch"
          git pull origin "$branch"
          EOF

      - name: Build frontend
        env:
          GITHUB_BRANCH: ${{ github.ref }}
        run: |
          ssh -T staging <<EOF
          branch="${GITHUB_BRANCH##*/}"
          cd "/www/infinite-closet/$branch/frontend"
          yarn install
          yarn run sts # generate strapi typescript models for frontend
          [ "$branch" -eq "main" ] && yarn run build
          EOF

      - name: Build backend
        env:
          GITHUB_BRANCH: {{ github.ref }}
        run: |
          ssh -T staging <<EOF
          branch="${GITHUB_BRANCH##*/}"
          cd "/www/infinite-closet/$branch/backend"
          yarn install
          [ "$branch" -eq "main" ] && yarn run build
          EOF
